    
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('Lzma', src, depend = ['PKG_USING_LZMA'], CPPPATH = CPPPATH)

Return('group')